[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solidity compiler settings
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

# EVM version
evm_version = "paris"

# Gas reporting
gas_reports = ["*"]

# File system permissions
fs_permissions = [{ access = "read-write", path = "./" }]

# Remappings for imports
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]

# Test configuration
[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false

# CI profile for faster builds
[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

# Local development profile
[profile.local]
optimizer = false
verbosity = 2

# RPC endpoints
[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
worldchain = "https://worldchain-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
worldchain_sepolia = "https://worldchain-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

# Etherscan configuration
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
worldchain = { key = "${WORLDSCAN_API_KEY}", url = "https://worldchain.blockscout.com/api" }
worldchain_sepolia = { key = "${WORLDSCAN_API_KEY}", url = "https://worldchain-sepolia.blockscout.com/api" }