name = "worldcoin-pooltogether-miniapp"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
dir = ".next"

pages_build_output_dir = ".next"